# Generated by Django 3.1.7 on 2021-03-30 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.TimeField()),
                ('updated_at', models.TimeField(blank=True, default=None)),
                ('deleted_at', models.TimeField(blank=True, default=None, null=True)),
                ('name', models.CharField(max_length=255)),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tag')),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.TimeField()),
                ('updated_at', models.TimeField(blank=True, default=None)),
                ('deleted_at', models.TimeField(blank=True, default=None, null=True)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('image', models.ImageField(upload_to='posts')),
                ('excerpt', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'posts',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.TimeField()),
                ('updated_at', models.TimeField(blank=True, default=None)),
                ('deleted_at', models.TimeField(blank=True, default=None, null=True)),
                ('name', models.CharField(max_length=255)),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category')),
            ],
            options={
                'db_table': 'categories',
            },
        ),
    ]
