# Generated by Django 3.1.4 on 2021-04-17 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210417_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='tag',
            name='created_at',
            field=models.TimeField(),
        ),
    ]
